/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ExploradorRouteImport } from './routes/explorador'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndicadoresIndexRouteImport } from './routes/indicadores.index'
import { Route as IndicadoresIdRouteImport } from './routes/indicadores.$id'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploradorRoute = ExploradorRouteImport.update({
  id: '/explorador',
  path: '/explorador',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresIndexRoute = IndicadoresIndexRouteImport.update({
  id: '/indicadores/',
  path: '/indicadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresIdRoute = IndicadoresIdRouteImport.update({
  id: '/indicadores/$id',
  path: '/indicadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/explorador': typeof ExploradorRoute
  '/favoritos': typeof FavoritosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/indicadores/$id': typeof IndicadoresIdRoute
  '/indicadores/': typeof IndicadoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/explorador': typeof ExploradorRoute
  '/favoritos': typeof FavoritosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/indicadores/$id': typeof IndicadoresIdRoute
  '/indicadores': typeof IndicadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/explorador': typeof ExploradorRoute
  '/favoritos': typeof FavoritosRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/indicadores/$id': typeof IndicadoresIdRoute
  '/indicadores/': typeof IndicadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/biblioteca'
    | '/configuracoes'
    | '/explorador'
    | '/favoritos'
    | '/relatorios'
    | '/usuarios'
    | '/indicadores/$id'
    | '/indicadores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/biblioteca'
    | '/configuracoes'
    | '/explorador'
    | '/favoritos'
    | '/relatorios'
    | '/usuarios'
    | '/indicadores/$id'
    | '/indicadores'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/biblioteca'
    | '/configuracoes'
    | '/explorador'
    | '/favoritos'
    | '/relatorios'
    | '/usuarios'
    | '/indicadores/$id'
    | '/indicadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ExploradorRoute: typeof ExploradorRoute
  FavoritosRoute: typeof FavoritosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
  IndicadoresIdRoute: typeof IndicadoresIdRoute
  IndicadoresIndexRoute: typeof IndicadoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorador': {
      id: '/explorador'
      path: '/explorador'
      fullPath: '/explorador'
      preLoaderRoute: typeof ExploradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores/': {
      id: '/indicadores/'
      path: '/indicadores'
      fullPath: '/indicadores/'
      preLoaderRoute: typeof IndicadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores/$id': {
      id: '/indicadores/$id'
      path: '/indicadores/$id'
      fullPath: '/indicadores/$id'
      preLoaderRoute: typeof IndicadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  BibliotecaRoute: BibliotecaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ExploradorRoute: ExploradorRoute,
  FavoritosRoute: FavoritosRoute,
  RelatoriosRoute: RelatoriosRoute,
  UsuariosRoute: UsuariosRoute,
  IndicadoresIdRoute: IndicadoresIdRoute,
  IndicadoresIndexRoute: IndicadoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
